/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113423-g00b288da73-20240125"
#endif /* AVUTIL_FFVERSION_H */
